[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."extract-pdf"]
  timeout = 26

[[headers]]
  for = "/src/*"
  [headers.values]
    Content-Type = "text/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200