[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."extract-pdf"]
  timeout = 26

[functions."extract-watchtower"]
  timeout = 26

[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200